### ISSUE TITLE
Improve registrations UI

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#113]
See https://github.com/cubing/worldcubeassociation.org/pull/111#discussion_r34417335. Right now, it's not super clear what's approved and what's pending.

**Comment by viroulep** [comment]
I have some other suggestions to improve the UI : 
 * Make the column width editable. For instance the "WCA id" and "name" fields are ridiculously large compared to the "guest"/"comments", it would be cool to change it on the fly.
 * Restore the "display mailing list" feature. Right now it's a mailto, but I'd love to be able to copy all the addresses so that I could copy them in cci.
 * Restore the "Edit" feature. I tried several "intuitive" things, but I can't seem to be able to edit a registration (such as the events one competes in), although I do have the write access to the comp.

**Comment by Mollerz** [comment]
I agree with Philippe's suggestions. Here are a few of my own:

 * Create divisions at a regular number of competitors (10 seems most sensible), so organisers and easily see how many total competitors are registered.
 * Add number tallies so we can see how many people are registered for each event. This allows us to make schedules more accurately, and I know some competitions limit the amount of competitors for an event so this is useful for them. Also add totals for accepted and non-accepted competitors.
   * On this, I'm assuming the random order of competitors was because of the trasnfer? I think adding a time/date of registration would actually be really useful. And just as the old competition edit page, by default make the registrations appear in order of registration.
   * Also perhaps allow us to order the registration list by either time/date of registration or alphabetically by first name, so it's easier to edit a registration if we need to.
 * Allow us to change the WCAID/Name/Country/Events of specific competitors. We often have people register for two competitions whilst they are new, and the WCAID does not update. Or people register months in advance for a competition, and decide they want to compete in extra events, or not compete in something they thought they would want to compete in. Also some people by default put the country of competition as their country, when they are only legible to compete for where they have citizenship.
 * I think it would be much better if we could make changes to the competition information after it has already been submitted - *only for delegates, not organisers*. A lot of organisers put the competitor limit, registration value, etc. in the information section of the submission form. It would be great if we could change this on the fly so people are always updated correctly. Often times venues also change, and some competitions have tentative events, so changing that would be useful as well. Currently to do all of this we need to contact the board, and a lot of these changes are reasonably trivial, but necessary for the competition. Reducing their workload seems sensible here.

**Comment by Mollerz** [comment]
Ok so we just opened up a new competition and we've discovered an oversight that is REALLY annoying to deal with.

Registration emails currently go to the first person on the organiser list. At UK competitions, we create a new email account for each competition, which all organisers and delegates have access to. If we want to have registrations go here, we have to create a WCA account with said email, and then put that under the organisers.

My suggestion to deal with this is to add a field under the organisers where you can put an email address where all registration related emails go to, without having to create a WCA account.

**Comment by jfly** [comment]
As of https://github.com/cubing/worldcubeassociation.org/commit/0f093c9c417e4d4c5ee8c4db29b874f3cda1a0b5#diff-0da243fb611c118a0cc4f87dee818233R358, *every* organizer is emailed, not just the first one in the list.

**Comment by Mollerz** [comment]
Oh it probably is the case, I just don't receive them as a delegate and we usually only have one set organiser.

**Comment by jfly** [comment]
Awesome. Feel free to add yourself as an organizer too.

**Comment by Mollerz** [comment]
I probably won't ever do that, we'll just make WCA Accounts with the competition email and list that as an organiser meanwhile.
