### ISSUE TITLE
Show custom display of organizers for the competition page

### ISSUE THREAD

**Issue by viroulep** [cubing/worldcubeassociation.org#125]
Since the switch to WCA account the organizers aren't shown on the competition webpage anymore (see https://www.worldcubeassociation.org/results/c.php?competitionId=ChamberyCube2015).

I think this should be fixed even if the organizers don't have a WCA account yet, since competitors may want to know/contact the organizers.

**Comment by jfly** [comment]
They *are* shown, you need to add them to the organizers textbox here https://www.worldcubeassociation.org/competitions/ChamberyCube2015/edit/.

**Comment by viroulep** [comment]
Yes sure but this is not what I meant : wouldn't it be better to keep the old field's value until the organizers are actually re-filled in by the delegates ?
Right now previous competitions still have their organizers filled in, but some (not all) upcoming competitions don't have organizers anymore.
Maybe I'm seeing it wrong and what I describe is already implemented (like until the delegate's account has been added, display the old field's value ?).

**Comment by SAuroux** [comment]
I fully agree with Philippe. But I will go a step further: We definitely
need this field to be able to accept different inputs than user accounts as
well. The fact that you are not able to enter something like "German
Nationals Orga team" without creating a dummy account (or by manipulating
the database) is a joke.

2015-08-04 20:00 GMT+02:00 Philippe Virouleau <notifications@github.com>:

**Comment by jfly** [comment]
@SAuroux, the idea here is that we're assigning *who* has access to this page. I'm not sure what you're proposing we have instead, but I don't see how it would be able to answer the question of who is allowed to access the page.

**Comment by SAuroux** [comment]
I think you are misunderstanding me Jeremy.

You can enter accounts there now to give certain people access, which is a
great thing, acknowledged.

IN ADDITION, I would like to be able to enter random stuff as well, *just
like that was the case before*. To repeat myself: The fact that you are not
able to enter something like "German Nationals Orga team" without creating
a dummy account (or by manipulating the database) is a joke. In such cases,
I simply want to list some random string linked to a mail address, not give
anyone access to anything.

2015-08-07 20:19 GMT+02:00 Jeremy Fleischman <notifications@github.com>:

**Comment by jbcm627** [comment]
Putting Sebastien's request another way, there should be a different (optional?) field for specifying what gets displayed for competition organizer(s).

**Comment by jfly** [comment]
Thanks for the explanatiaon, Sebastien. I understand what you're asking for. From a historical perspective, I feel that seeing "German Nationals Orga team" as the organizer of [GermanNationals2015](https://www.worldcubeassociation.org/results/c.php?i=GermanNationals2015) is particularly uninteresting. I would be much more interested in seeing the names of the team members rather than the name of the team (of *course* US Nationals was organized by the US Nationals Organizing team!) People who go to the great effort of being a competition organizer deserve to have their names recorded on our website (especially for herculean competitions such as Worlds).

That all said, it does make sense that you'd want a single email for people to contact the organization team, however. How about an additional field to specify contact information?

**Comment by SAuroux** [comment]
Hey Jeremy. Ok, listing organisers by name as well makes sense, granted.
However, adding the organisers individually also automatically links the
mail addresses for all of them. So to stay with the GermanNationals2015
example, there would be 4 organisers with individual mail adresses + one
additional contact address to reach all. That doesn't seem very expedient
to me.

If I wanted to list all organisers in the old form, my input would have
been something like "name1, name2, name3, name4. ([{Contact}{orga@comp.de}]).
With the new form however, such an input is no longer possible. That kind
of sucks, as this basically means, that a useful feature got lost during
this transition.

What you need to understand is the fundamental difference between the
delegate filed and the organiser field.

- The delegate field always required individual persons to be listed and a
contact mail adress makes sense here of yourse. Also, the delegate
definitely shoud have access to the competition page. hence, the new system
works perfectly for this field.
- The organiser field however is different. It doesn't always make sense to
list individual people (what if a huge organisation is the official
organiser of a competition?) and also it doesn't always make sense to list
the mail contact information for every individual organiser. In addition,
it is not always necessary for organisers to have access to a competition
page, especially not if the WCA registration system is not used for that
competition.

As a result, the freedom provided by the old system for the organiser field
was indeed useful and is now missing.

2015-08-11 11:40 GMT+02:00 Jeremy Fleischman <notifications@github.com>:

**Comment by jfly** [comment]
I just talked to @SAuroux about this online, and we came to the following agreement:

1. A policy of requiring all organizers to be explicitly listed (rather than something like [JRCA](https://www.worldcubeassociation.org/results/c.php?i=Japan2005), [Winning Moves France](https://www.worldcubeassociation.org/results/c.php?i=France2004), or [US Nationals Organizing Team](https://www.worldcubeassociation.org/results/c.php?i=USNationals2015)) is probably best, but should be discussed with the board, rather than enforced by this code change.
2. All competitions will get a contact form. That contact form will contact all organizers, or an optional contact email.

**Comment by jbcm627** [comment]
I disagree with this to some extent. I think it is fine to list all organizers, but if we do, I would strongly prefer personal contacts of organizers not go up under a "contact information" section. Eg for US Nationals, I'd much rather direct people to the CubingUSA contact form, which the organizers have much more control over.

What about a separate customizable field for contact information?

**Comment by jfly** [comment]
Ok, after talking to Jim, being able to specify a contact field with arbitrary text is probably best. Just to keep things interesting, we'll use markdown for this, rather than the [{}{}] syntax. Looks like our markdown renderer, redcarpet, allows us to escape all html tags (see escape_html on https://github.com/vmg/redcarpet).

**Comment by SAuroux** [comment]
Any news on this?

A minute ago I had to edit the delegates for a competition and now the
entry for the organiser has vanished, as this was a pre-update comp and the
organiser was entered in a pre-update fashion. This is eytremely annoying.
:/

2015-08-11 19:00 GMT+02:00 Jeremy Fleischman <notifications@github.com>:

**Comment by jbcm627** [comment]
Pull request was just merged regarding this. Deploying doesn't work right
now though, and I don't have time to figure out why, so will wait on that.

**Comment by jfly** [comment]
I've deployed this. There is now a `contact` field on every competition. I've copied the wcaDelegate field over to the `contact` field for every competition without entries in the `competition_delegates` table by running the following ruby code:

```ruby
Competition.all.select {|c| c.organizers.length == 0 }.each { |c| c.update_attribute(:contact, c.organiser) }
```

As soon as Pedro finishes #59, we'll get rid of the wcaDelegate and organiser columns for good.

**Comment by SAuroux** [comment]
Please do not delete these columns soon! We should be sure that everything
works well before we get rid of the old data.
Am 21.08.2015 18:28 schrieb "Jeremy Fleischman" <notifications@github.com>:

**Comment by jfly** [comment]
The columns are gone. We have database backups if anything looks wrong.
