### ISSUE TITLE
Admins and WCA delegates should be able to change user passwords

### ISSUE THREAD

**Issue by gagou9** [cubing/worldcubeassociation.org#131]
I'm currently with Hippolyte Moreau and Antoine Piau and one has lost his password, I though "well I can change it I guess", but I actually couldn't ;)
What do you think?

**Comment by jbcm627** [comment]
There is a password reset:
https://www.worldcubeassociation.org/users/password/new
Did you have a use case in mind for which an administrator setting the password is better?

**Comment by lgarron** [comment]
No one should ever be able to know (let alone set) another's password like
this.
Way too much opportunity for abuse/social engineering, especially if we
give the ability to all delegates.
We should handle individual issues case-by-case unless we start finding
patterns we need to address.

Since there is already a reset form, I don't think we need to give admins a
new ability.

**Comment by jfly** [comment]
Agreed with Lucas and Jim. Reset via email should be good enough. Closing this issue. Gael, I'd you have any information about why reset via email didn't work for them, that would be good to know.

**Comment by gagou9** [comment]
Nope, they definitely could have used the lost password button for sure ;)

I was wondering, as in many many softwares admins/moderators/techies can
change passwords (not see current passwords of course). It's just a
feature that's not needed but sometimes useful (even thou I think the
reset password option is fine as well)
