### ISSUE TITLE
Better organization of the /delegates list

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#166]
From Shelley:

> I think it might make sense to have a list of links to each section/region at the top of the delegates page. Mostly because it's weird that Eastern and Western USA are separated by so much distance on the delegates list, and people looking for American delegates might stop at the first section they find and think that's all. In fact, Bob Burton completely left out the Western USA delegates when putting together the US delegates mailing list a while ago.

This seems like a good candidate for a mentored project. #93 could possibly be done along with this?

**Comment by pingskills** [comment]
This page is actually grouped by Senior Delegates rather than regions. It lists each Senior Delegate with their delegates as a table. So we could put a list of the regions for each Senior Delegate at the top but I'm not sure it achieves much.

The Senior Delegates are listed in the order of their region so we could simply update the region names if we wanted to sort them in a particular order. eg (USA East, USA West).

Let me know if you have any suggestions on the best way to proceed with this issue.

**Comment by jfly** [comment]
Yeah, senior delegates basically define regions.

Good idea about renaming the regions to achieve better sorting! Can you send an email to the Board with that proposal and cc the software team? I'm going to go ahead and close this issue. It's too vague, and we've got more important stuff to do =).
