### ISSUE TITLE
Nothing prevents setting anyone as a delegate for a competition

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#291]
We currently don't validate that competition delegates are actually delegates. This is in order to support editing old competitions with delegates who may no longer be delegates.

**Comment by pedrosino** [comment]
Maybe validate this on update/create? Would that allow us to insert an old delegate via SQL?

**Comment by jfly** [comment]
Yeah, nothing we do in rails would prevent a SQL update, the problem is that if we validate on update and you were to try to edit change something in an old competition through the form, Rails would not let you.

**Comment by pedrosino** [comment]
I thought there was something on the form like "must be: delegate" or
"only: delegate"...Will check.

The behavior you described sounds right to me.
Em 04/01/2016 19:13, "Jeremy Fleischman" <notifications@github.com>
escreveu:

**Comment by SAuroux** [comment]
I had exactly this problem a few minutes ago. I noticed that I was listed as second delegate for FranconiaWinter2013, even though I did not attend the competition in the end. But I could not edit this within the admin interface, since the other delegate (Björn Korbanka) of the competition is no longer an active delegate.
