### ISSUE TITLE
Have user prove that they know their DOB before they can claim a WCA ID

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#292]
AFAIK, There are two tricky things here:

1. Persons without birthdates.
2. Accidentally creating an attack vector for guessing people's birthdates.

Item 1 can be handled by just letting people claim a WCA ID for WCA IDs without birthdates.

Item 2 could be handled by implementing some sort of retry/backoff mechanism, but this doesn't seem worse than the PHP birthdate verification for profile picture uploading thing we used to have. @pochmann, @jbcm627, @Baiqiang, do you remember how that worked?

**Comment by SAuroux** [comment]
Concerning item 1, I strongly prefer a different approach.

In a perfect world, we should have the DOB of every competitor. If we are
missing one, then usually because there was no decent way to obtain it
after a competition has ended. But if someone with a missing DOB ever gets
a WCA account and tries to claim his WCA ID, this gives us a decent way.

So please, if someone with a missing DOB wants to claim a WCA ID, make him
contact the results team so that we can add his DOB before he can claim his
WCA ID.

2016-01-02 19:22 GMT+01:00 Jeremy Fleischman <notifications@github.com>:

**Comment by jfly** [comment]
Good idea, @SAuroux! I've implemented this [here](https://github.com/cubing/worldcubeassociation.org/commit/4968832e51c020f457d61db1350a4c06d4897208) and here's a screenshot:

![screenshot_2016-01-02-13-21-20 477](https://cloud.githubusercontent.com/assets/277474/12076131/f8de40ec-b153-11e5-8161-b3250d14fd46.png)
