### ISSUE TITLE
Log user_id

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#339]
I'm not sure what the right way to do this is. http://stackoverflow.com/questions/10811393/how-to-log-user-name-in-rails has a bunch of scary looking examples.

@timhabermaas, any ideas here?

**Comment by timhabermaas** [comment]
If you just want to log the user id somewhere in the logs, you could add logging to a `before_action` in `ApplicationController` or use a [custom middleware](http://stackoverflow.com/questions/10811393/how-to-log-user-name-in-rails#comment37772865_11102061).

Extending Rails' logging middleware isn't straightforward since the session middleware which parses/decodes/decrypts the session information comes afterwards, so you can't easily access the session yet. That's why the accepted solution reorders the middleware stack.

I think I'd just add a custom middleware and call it a day. Ping me if you want me to implement it.

**Comment by jfly** [comment]
I see. Thanks for the explanation. A custom middleware sounds good to me. Could you take that on?
