### ISSUE TITLE
Don't allow (birthdate > Date.today)

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#352]
Roman suggested this. I see no issue with it.

**Comment by pedrosino** [comment]
What do you mean with "don't allow"?

**Comment by timhabermaas** [comment]
This confused me as well at first. It means: "Don't allow (birthdates in the future)" or "Don't allow (birthdate > `Date.today`)"

**Comment by jfly** [comment]
I did not realize the multiple possible interpretations! Updated the title =)

**Comment by jfly** [comment]
Funny story from @Luis-J-Ianez:

> Then I asked him to check whether the system was prompting for DD-MM-YYYY or MM-DD-YYYY, but this didn't help either as he was entering the correct format.  After being (both, he and me) lost for a while in WhatsApp, I decided to make a phone call so that I could feel his thoughts.  All you know me a bit, I really enjoy this. :P  And here it comes the funny part, hahaha.

> Me -- So, what date are you providing the system?
> He -- "12-07-2016"
> Me -- What the...?  Will you be born in the future???
> He - What???  The system is asking my birthday....
> 
> I'm not sure that the joke sounds also funny in English.  The fact is that for a Spaniard, date of birth and birthday sounds quite similar, while in Spanish the terms have nothing to do: "fecha de nacimiento / cumpleaños".  Additionally, someone expecting a verification check from a website, thinking about providing your "next birthday" as a confirmation piece of data is far from being completely illogical.
> 
> Take your own conclusions.  I still think that improving this will make our lives way easier in the future.
> 
> Just for your information (and rejoice :P )
> Regards,
> 
> - Luis

**Comment by pedrosino** [comment]
I received feedback from a brazilian delegate that people were entering the wrong DOB when creating an account. This happened because instead of clicking the calendar and picking the date, they would type "25/02/1990" and it would become 2025-02-19.

In Brazil we used DD/MM/YYYY (or YY) so my guess is that this format (with no hint as it currently is) will cause a lot of trouble. If the person has already competed, we're fine because once we assign the WCA id it will import the correct DOB. But for newcomers this can be a problem.

My suggestion: 
1 - remove the datepicker here (and at https://www.worldcubeassociation.org/profile/claim_wca_id too). If you're old like me, you have to click 26*12 times to find the year you were born, and that's not very fun. I'd rather have the user just type in the value
2 - change it to a regular text field and tell the user what is the correct format. This could also be checked on spot with jquery/javascript (like not allowing year > now or month > 12).
2.1 - not sure if a single textbox or 3 of them is better, since we store the 3 values separated anyway

**Comment by timhabermaas** [comment]
What about disabling the text box and only allowing the datepicker as a way to input data (only if JS is enabled)? Expecting the user to keep a specific format will always lead to issues no matter how good your hints or parsers are.

> not sure if a single textbox or 3 of them is better, since we store the 3 values separated anyway

3 dropdown lists are reasonable fast to operate (click + `11<Enter>`) and don't have the problems mentioned above.

**Comment by pedrosino** [comment]
I don't like the datepicker because if you were born in 1950, you'd have to navigate through a LOT of months (we only allow navigation through months now).

Maybe have the field auto-complete the format as you type would be good too?

Anyway, I'm sending a PR with a hint for the field and a simple validation (year < Date.today.year) until we decide on the rest.

PS.: Should we require a minimum age? I don't see kids < 1 year solving a cube, but who knows?

**Comment by timhabermaas** [comment]
I didn't know our datepicker makes it hard to go to a specific year. No wonder people want to rather use the text field.

> Maybe have the field auto-complete the format as you type would be good too?

This reminds me of http://www.commitstrip.com/en/2016/01/19/how-to-keep-a-young-coder-occupied/ (tl;dr it's hard/impossible to get it right).

> Should we require a minimum age? I don't see kids < 1 year solving a cube, but who knows?

I wouldn't. `>0` is not as arbitrary as 1 year.

**Comment by pedrosino** [comment]
I've seen quite a few uses of the auto-format thing I mentioned and they seem to work (we use it here for birth dates and the "CPF" - similar to the US social security number, which is xxx.xxx.xxx-xx). What exactly is impossible to get right?

**Comment by timhabermaas** [comment]
> What exactly is impossible to get right?

The number of possible states you can end up in are huge. Even something as simple as `hh:mm` gets tricky if backspace and cursor keys (or using your mouse to manually set the cursor) are allowed. Trust me, I tried. ;) But it's a pretty good exercise in self-control.

It took me 5s to break the [maskjs plugin](http://bguzmanrio.github.io/maskjs/): In the `hh:mm` textbox, set the cursor next to the `:`, press backspace and tab out of it: no validation errors even though the `:` is missing. If you want to manually reinsert the `:` you can't. You can't even remove digits from the back anymore.
I don't say this to make maskjs look bad, but just to demonstrate that it's harder than it looks.

**Comment by pedrosino** [comment]
Haha, that was a fun one.
Maybe the plugin can be improved?

I guess you're right about the infinite possible moves people can make...still, I'd like to get rid of the datepicker here :P

Maybe 3 selectors or 3 text fields would be the cleanest way.

**Comment by jfly** [comment]
I have yet to see a datepicker I really like, so I guess I'm on @timhabermaas's side here. @pedrosino, if you're motivated to look into this stuff, then I'm probably willing to accept a PR here. My highest priority is consistency (I'd really like for us to use the same thing everywhere).

**Comment by pedrosino** [comment]
Yeah, consistency is good. My concern is that in other places, we usually "travel" two or three months at most. For birthdates it can be many many years...

How do you feel about 3 selectors instead?

**Comment by jfly** [comment]
Hmm...3 dropdowns (the Rails default) really annoys me, because you can't type "15", you have to scroll a bunch to find it. I'm sorry, I know I'm just complaining about everything here and not providing ideas for improvement.

**Comment by pedrosino** [comment]
I'm fine with 3 textboxes too :)

**Comment by timhabermaas** [comment]
> because you can't type "15"

You actually can (at least in Chrome). `15<Enter>` works if the dropdown has focus (e.g. set by `<Tab>`). You don't need to open any dropdown menu to enter day, month and year.

**Comment by jfly** [comment]
@timhabermaas, that's a fair point, but it's not obvious, and you can't backspace.
