### ISSUE TITLE
Registration emails come from notifications@worldcubeassociation.org

### ISSUE THREAD

**Issue by pedrosino** [cubing/worldcubeassociation.org#364]
...and encourage people to reply. But problems regarding registrations should be addressed with the delegate/organizer, so maybe it would be better to have the e-mail sender be the organizer/delegate/contact.

**Comment by jfly** [comment]
Hmm... which eamils in particular are you having trouble with? I specifically set the reply_to header so that people should actually find that they're replying to the competition "managers" (organizers + delegates) when they hit reply. See https://github.com/cubing/worldcubeassociation.org/blob/35e7b66c8ae68faeb4ad839c9a1a2c38a70f20ca/WcaOnRails/app/mailers/registrations_mailer.rb#L10 and the many other lines of code like it in RegistrationsMailer. The same thing happens with any WCA ID claims you may receive as a delegate.

Changing the email sender to the organizer/contact will run the risk of spam detection, as we're not truly the people we'd be pretending to be. @gagou9 knows more about this stuff than I do.

**Comment by pedrosino** [comment]
This is already being done, so we can close the issue.

**Comment by jfly** [comment]
Ok, please reopen if the board continues to get lots of email, we'll have to figure out some other solution.
