### ISSUE TITLE
New dates fields are buggy =(

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#376]
@pedrosino introduced some changes to our date fields in #370. Now that the change is in, I am seeing some weirdness, unfortunately.

Note how the field is not taking up 100% as its fellow fields are:

![2016-02-05_662x794_kaladin](https://cloud.githubusercontent.com/assets/277474/12857267/07605e88-cbfe-11e5-9cea-672f466784d9.png)

More importantly, the warning shows up as desired, but it doesn't go away when you fix the field! Also notice that it's pretty annoying to get the date popup to reappear now (you have to click outside of the field, and then click back inside the field). I feel that we should blur the field when you select a date, that way you can just click back on the field to bring the popup back up:

![smaller](https://cloud.githubusercontent.com/assets/277474/12857759/d4b0170a-cc00-11e5-8b75-62899a669a0f.gif)

@pedrosino, would you look into this? Thanks!

**Comment by pedrosino** [comment]
Ok, I think I see the problem here

If you start with an empty date and type a wrong date and tab out, it will flash the alert.
Then you click, erase the wrong date and input a valid one, tab out, the alert goes away.

However, if you start with a date on the field, and type something wrong, the old date will remain assigned on the calendar. So once you fix it to the same date as initially, the dp.change will not fire, because the date didn't change!
You can see that on Jeremy's gif. Once he clicks after the alert, January 1st is still selected. So removing the "a" will not change the date at all.

I currently don't have a good clue on how to fix that...

**Comment by pedrosino** [comment]
About the format, the problem seems to be here: https://www.diffchecker.com/fcfyjmzr
The missing classes on the inner div AND the missing <span> with the button cause the text field to be small and ugly :P

**Comment by pedrosino** [comment]
I tried many different things (using the dp.hide event, using data.("DateTimePicker").date($(this).val()) to force a dp.change) but no success.

Thinking about it, the "normal" use cases are:
1 - you have an empty date (creating a user) -> this works, because there is no previous date for the picker to default to when you enter an invalid date.
2 - you are editing a previously saved date -> this will probably work, because you wanna save a different date (or at least you should, otherwise why are you editing?). So if you enter an invalid date, the picker will still have the old saved value, and once you type the new correct one, it will remove the danger stuff.

Conclusion: it doesn't work in our smarty test, but for regular use it will probably be fine :)

**Comment by pedrosino** [comment]
I just made a new commit, using .on('blur') and regex matching to check the date, instead of the plugins methods. (see https://github.com/pedrosino/worldcubeassociation.org/commit/2e913c612522aaa8e9dc0931b7b556f26a50965c )

I tested Jeremy's example and now it works as intended.
