### ISSUE TITLE
Registration for non-visible competitions

### ISSUE THREAD

**Issue by Luis-J-Ianez** [cubing/worldcubeassociation.org#415]
Registration for non-visible competitions should be not accessible. Picture this: as a delegate, I have just requested a competition, but it's still pending Board approval.  As the URLs for registration are predictable, my website has already the links accessible.  So, clicking these links people can register to a non-announced, non-visible competition.

**Comment by jfly** [comment]
Good catch, Luis!

Why are you creating an invisible competition with registration open? Shouldn't you set the registration_open datetime to a point at which you really are ready for people to register?

This would make a great mentored project. We already have a test that people cannot register for a competition whose registration is not yet open, but we don't have a test that checks that people cannot register for a competition which is not yet visible: https://github.com/jfly/worldcubeassociation.org/blob/2bfd05339fe1e7a6b0a3cf1aa908920665d41c45/WcaOnRails/spec/controllers/registrations_controller_spec.rb#L186-L194

**Comment by jfly** [comment]
From Olivér:

To answer Jeremy's question here: We would like to open registrations right away, and since we cannot know when the Board will approve the competition, we can't possibly set a perfect time in advance.

**Comment by pingskills** [comment]
It turns out that the code actually stops a competitor from visiting a non-visible competition and it's registration page. A delegate can however. So I think no code changes are required here. Instead I think we should create 2 tests:

1. Ensure a competitor cannot register for a comp that is not visible
2. Ensure an organizer can register for their own competition
