### ISSUE TITLE
Confusing error when creating new competition

### ISSUE THREAD

**Issue by timreyn** [cubing/worldcubeassociation.org#416]
I created a new competition for NortheasternSpring2016 at https://www.worldcubeassociation.org/competitions.  I forgot that you're supposed to put the name of the competition, not the competition ID, so I entered "NortheasternSpring2016" into the "name" field and hit "submit".

At the top of the page I got a very confusing error message:

The form contains 6 errors:
Id can't be blank
Id is invalid
Name is invalid
Name can't be blank
Name is invalid
Competition nickname is invalid

This is way too many errors for forgetting two spaces, and none of them really say what I did wrong.  Also, "Name is invalid" came up twice.

Below the "name" field is a better error message: "The full name of the competition including the year at the end (e.g., European Rubik's Cube Championship 2006). Be sure to capitalize."  But it's not in a big red box, so I didn't notice it for about a minute.

**Comment by jfly** [comment]
A screenshot is sometimes worth a thousand words:

![image](https://cloud.githubusercontent.com/assets/277474/13692170/d7991814-e6f3-11e5-870c-e0d274d3096e.png)

I think the red text under the name field *is* nice, but that big red box distracts from it.

I added the overwhelming quantity of errors in db47b959928472384726ab94f1b094bebd19a794. The problem is that when you're cloning an old competition, there can be something wrong with that old competition, and since we don't show all the fields in this form, we need to either be okay with not showing them at all (which can be confusing), or we need to show them all on top in a big red box (which can also be confusing, as Tim just mentioned.

I'm honestly not sure what's best to do here. It might be okay to continue doing what we're doing, but explicitly hide any errors related to id and nickname. I'm not sure why there are two error messages for `Name is invalid`.

**Comment by pingskills** [comment]
If we are going to keep the same workflow then hiding any messages not related to the name is a good option.

Alternatively we could change the create page to have all the fields present. To clone a competition you could go to the list of competitions and if you have permission to create competitions, add a link which would bring up the create competition page with all the relevant fields populated.

**Comment by timhabermaas** [comment]
This might be a good opportunity to remove that confusing `attr_accessor :competition_id_to_clone; before_validation :clone_competition` code from `Competition`. Representing that form as one object (using `ActiveModel`) which has its own validation rules might clean up the code and the error messages at the same time.

**Comment by jfly** [comment]
I like @pingskills idea to get rid of that competition autocomplete we have right now. Sharing the new page with the edit page also sound clean to me :)
