### ISSUE TITLE
Unable to complete competition submission

### ISSUE THREAD

**Issue by ShadenSmith** [cubing/worldcubeassociation.org#441]
I started a competition submission this morning but closed the browser and decided to come back to it later. That unfinished competition now appears under my competitions, making me unable to continue editing. I had not filled in the date before closing the browser, so the date shows up as 2015.

Minnesota Cube Melt 2016:
![comp_page](https://cloud.githubusercontent.com/assets/620322/14094692/20d9f510-f51e-11e5-9768-f7e821998fd1.png)

And when I click on that competition:
![error_page](https://cloud.githubusercontent.com/assets/620322/14094694/30b941f2-f51e-11e5-9ea9-14f37ab21666.png)

On the new competition page, it shows up as available to clone. But I don't see any way to edit it.

**Comment by jfly** [comment]
Ah, that is confusing. Try <https://www.worldcubeassociation.org/competitions/MinnesotaCubeMelt2016/edit>.

The competition you created exists, but is not marked as publicly visible. That's why you got this "Unknown competition ID" message when you tried to view the competition.

This should become less confusing after #407 is merged up. We'll instead show a "this competition is not yet publicly visible" alert on the top of the page when a competition manager tried to view the competition.

**Comment by jfly** [comment]
Thank you for the detailed bug report along with screenshots!

**Comment by ShadenSmith** [comment]
Ah, the edit page worked fine. Since the unfinished competition showed up in 'Past Competitions', it did not have an edit link. Is it possible to find the edit page for that competition without knowing the URL you gave me?

Thanks for the help!

**Comment by jfly** [comment]
You should have a notification for every unconfirmed competition. See:

![image](https://cloud.githubusercontent.com/assets/277474/14129180/8fc3019c-f5dc-11e5-8681-574163e7e638.png)

Can you test out whatever you did again and let us know if you're not getting that notification?
