### ISSUE TITLE
Intermittent failure in rspec ./spec/features/sign_up_spec.rb:86

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#475]
```
Failures:
  1) Sign up when signing up as a first time competitor can sign up
     Failure/Error: u = User.find_by_email!("jack@example.com")
     ActiveRecord::RecordNotFound:
       Couldn't find User
     # ./spec/features/sign_up_spec.rb:108:in `block (3 levels) in <top (required)>'
Finished in 56.85 seconds (files took 3.62 seconds to load)
377 examples, 1 failure
Failed examples:
rspec ./spec/features/sign_up_spec.rb:86 # Sign up when signing up as a first time competitor can sign up
Randomized with seed 6827
/home/travis/.rvm/rubies/ruby-2.2.3/bin/ruby -I/home/travis/build/cubing/worldcubeassociation.org/WcaOnRails/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.2.3/lib:/home/travis/build/cubing/worldcubeassociation.org/WcaOnRails/vendor/bundle/ruby/2.2.0/gems/rspec-support-3.2.2/lib /home/travis/build/cubing/worldcubeassociation.org/WcaOnRails/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.2.3/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
The command "bundle exec rake" exited with 1.
19.71s$ bundle exec pre-commit run git
No failed checks.
```

**Comment by jfly** [comment]
Here's what the test looks like right now:

```
      click_button "Sign up"

      u = User.find_by_email!("jack@example.com")
```

Perhaps there is a race between clicking the "sign up" button and the User actually getting created? Debugging this would probably require a degree in Capybara...

**Comment by timhabermaas** [comment]
> Perhaps there is a race between clicking the "sign up" button and the User actually getting created? 

That's probably the case. The web server runs in it's own process (separate from RSpec), so the transaction which submits the user to the DB might not be commited yet. This can be solved in several ways:

* Add some Capybara expectations (e.g. check for a flash message) after clicking the Sign up button which forces the RSpec process to wait.
* Instead of querying the DB check if the user has been registered by using the page (e.g. login with admin and visit users page? let user login?)
* ???

**Comment by timhabermaas** [comment]
> The web server runs in it's own process (separate from RSpec)

Btw. that's only true when using Capybara's JavaScript driver.
