### ISSUE TITLE
Merge competitors

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#72]
(from https://github.com/cubing/wca-website/issues/14#issuecomment-78203129)

It happens quite often that competitors end up with multiple accounts, most of the time because they don't enter their WCA ID upon registration. Once they have multiple accounts it is quite annoying to merge them in the database.

As a result I would like to see a script for this, which could look as follows:

"Please enter the WCA IDs you want to merge. Both profiles will be merged into id1."

id1: __________ id2: __________

```sql
UPDATE Results SET personId=id1, personName=name1, countryId=country1 WHERE personId=id2;
DELETE FROM Persons WHERE id=id2
```

**Comment by SAuroux** [comment]
Any news on this? I am asking because we had such a case recently and doing this manually caused minor trouble internally.

Also, there is something missing in tthe code I proposed at the time:

Code: 
UPDATE Results SET personId=id1, personName=name1, countryId=country1 WHERE personId=id2;
DELETE FROM PersonsWHERE id=id2

name1 and country1 need to be retrieved from the Persons table (id=id1)

**Comment by SAuroux** [comment]
Oh, good catch. Well, common sense would be to merge all subIds of person2
into the last subId of person1.

But in practise: I cannot imagine ever using this for people with subIds,
as this usually affects 2nd or 3rd time competitors that failed to register
properly for their subsequent competition. So I would be fine with any kind
of error like "Cannot do it, since person 1/2 has subIds."

2015-11-16 21:47 GMT+01:00 Jeremy Fleischman <notifications@github.com>:

**Comment by jfly** [comment]
Bailing out if someone has multiple subIds seems like a good plan to me! I'll look into this today or tomorrow.

**Comment by SAuroux** [comment]
Something with the confirmation text seems to be wrong. I just ot the following: "Successfully merged 2015MEHR05 into 2015MEHR05!"

**Comment by jfly** [comment]
Thanks for checking! Stupid mistake on my part. Fixed [here](https://github.com/cubing/worldcubeassociation.org/commit/db26fef9c084dcb06a4475fbcf06383c50d9b3ef)
