### ISSUE TITLE
Admin competition view asks if I want to leave

### ISSUE THREAD

**Issue by pedrosino** [cubing/worldcubeassociation.org#790]
(Sorry, couldn't think of a better title)

When I'm at competition/edit/admin, even if I don't change anything it shows a pop-up asking if I really want to leave if I try to close the window.
I thought it was just with me, but @Luis-J-Ianez reported the same behaviour. It didn't happen some time ago (not sure how long).

**Comment by jonatanklosko** [comment]
Interesting, this doesn't happen for me.

**Comment by jfly** [comment]
Could you provide a direct link, @pedrosino? This issue might be competition specific. I just tried https://www.worldcubeassociation.org/competitions/LegendsofRubik2016/edit/admin on both Firefox and Chrome, and I was unable to reproduce this issue.

**Comment by pedrosino** [comment]
Indeed that link has no problem for me. I'll let you know when I run into
it.

**Comment by Luis-J-Ianez** [comment]
https://www.worldcubeassociation.org/competitions/Weekend162016/edit/admin

Firefox - Ubuntu
Non-visible comp (which might be the key point)

**Comment by jonatanklosko** [comment]
Gotcha!
It happens when *I would like to use WCA website instead of an external one for additional informations.* is checked. [Here are the two lines which cause this](https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/app/assets/javascripts/competitions.js#L9-L10). I think that we don't have to disable the input because of [this callback in the `Competition` model](https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/app/models/competition.rb#L304-L307). I'll make a PR for this in a moment.
