### ISSUE TITLE
Links in competition tabs seem to use relative URLs

### ISSUE THREAD

**Issue by BiscuitCubed** [cubing/worldcubeassociation.org#814]
I had a link where the URL was worldcubeassociation.org/competitions/KCubingSummer2016/register. When clicked it took you to

https://www.worldcubeassociation.org/competitions/www.worldcubeassociation.org/competitions/KCubingSummer2016/register

I've changed it to /competitions/KCubingSummer2016/register and now it works

**Comment by jonatanklosko** [comment]
I think this is expected behavior. If you type `www.google.com` it will refer to `https://worldcubeassociation.org/www.google.com`. That's because it's missing protocol part.
Summary doing `[Click](https://www.worldcubeassociation.org/competitions/KCubingSummer2016/register)` works.
Relative path is good as well anyway.
So I think it's not real issue, right? =)
