### ISSUE TITLE
Localization of Countries/Events/Continents

### ISSUE THREAD

**Issue by viroulep** [cubing/worldcubeassociation.org#875]
Localization of Countries/Events/Continents
So I did not include these in #874 because @pingskills is already refactoring these 3 models.
You can find my initial idea in this [commit](https://github.com/viroulep/worldcubeassociation.org/commit/563a51ef9cb00b7ca8bd925c6163bce497164fd1).

My implementation relied on the `i18n-country-translations` gem, with an locale extensions for our "Multiple Countries (Continent)". There is one major thing though, in this gem the country name in English for the USA is "United States", which may be an annoying change.

Another side effect of translating the countries can be found [here](https://github.com/viroulep/worldcubeassociation.org/commit/563a51ef9cb00b7ca8bd925c6163bce497164fd1#diff-2c543e1650c254ecc83a33005c769c7fR1083):
> We want a localized country name, but a constant id across languages
 NOTE: it means "search" will behave weirdly as it still searches by English
 name (eg: searching for "Tunisie" in French won't match competitions in
 "Tunisia" even if the country displayed is actually "Tunisie"...)

The overall result looks very nice though :)

Any opinion on how to do this part?

**Comment by jfly** [comment]
The only reason searching for "Tunisia" even works right now is because our database has this `countryId` column that contains the English name of the country. See https://github.com/cubing/worldcubeassociation.org/blob/54194f897fad85bb5eac393cd4ae46e53f1a5650/WcaOnRails/app/models/competition.rb#L745.

Once we've gotten rid of our PHP code, we're going to start doing some serious database migrations, and this `countryId` column will be renamed to `country_iso2`, which will break searching anyways. I don't know what a good solution to this would be. Moving the search out of the database and into our application seems slow. Maybe it'll finally be time for something like ElasticSearch.

Either way, I don't think you should let this block you making this improvement. The only reason searching for "Tunisia" even works right now is because of our silly database schema.
